DROP TABLE IF EXISTS Booking_Info;


CREATE TABLE Booking_Info (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  departure_Time VARCHAR(250) NOT NULL,
  destination VARCHAR(250) NOT NULL,
  seatNr VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS TBL_EMPLOYEES;


CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

